[package]
name = "ch04"
version = "0.1.0"
edition = "2021"

[dependencies]
candle-core = { workspace = true }
candle-nn = { workspace = true }
tracing-chrome = { workspace = true }
tracing-subscriber = { workspace = true }
